# ./apps/app1/kustomization.yaml
resources:
  - virtualservice.yml

# Define custom configuration for the app (host and exact URL)
configMapGenerator:
  - name: app1-config
    literals:
      - host=app1-example.com
      - exact_url=/app1-service