apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-dev-virtualservice
spec:
  http:
  - match:
    - uri:
        exact: /simple-dev-virtualservice
    route:
    - destination:
        host: simple-dev-virtualservice
        port:
          number: 80
