# ./apps/app3/kustomization.yaml
resources:
  - allow-intra-namespace.yaml
  - configmap.yaml

replacements:
  - source:
      kind: ConfigMap
      name: app2-config
      fieldPath: data.AUTH_POLICY_NAME
    targets:
      - select:
          kind: AuthorizationPolicy
        fieldPaths:
          - metadata.name
  - source:
      kind: ConfigMap
      name: app2-config
      fieldPath: data.NAMESPACE
    targets:
      - select:
          kind: AuthorizationPolicy
        fieldPaths:
          - metadata.namespace
          - spec.rules[0].from[0].source.namespaces[0]