apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-app-helmchart-virtualservice
  namespace: argocd
spec:
  project: default
  source:
    repoURL: pxsacr.azurecr.io
    targetRevision: "0.1.*"
    chart: helm/demo-virtualservice
  destination:
    server: https://kubernetes.default.svc
    namespace: ind-ns1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
