apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: $(AUTH_POLICY_NAME)
  namespace: $(NAMESPACE)
spec:
  selector:
    matchLabels: {}  # This allows all services within the namespace (ind-ns1)
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["$(NAMESPACE)"]  # Allow only traffic from the same namespace (ind-ns1)
