apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: AUTH_POLICY_NAME_PLACEHOLDER  # Will be replaced dynamically
  namespace: NAMESPACE_PLACEHOLDER    # Will be replaced dynamically
spec:
  selector:
    matchLabels: {}
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["NAMESPACE_PLACEHOLDER"]  # Will be replaced dynamically
