apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: auth-policy-02 # Will be replaced dynamically
  namespace: ind-ns1  # Will be replaced dynamically
spec:
  selector:
    matchLabels: {}
  action: ALLOW
  rules:
    - from:
        - source:
            namespaces: ["ind-ns1"]  # Will be replaced dynamically