# ./apps/app2/kustomization.yaml

resources:
  - allow-intra-namespace.yaml

replacements:
  - source:
      kind: Namespace
      name: ind-ns1
      fieldPath: metadata.name
    targets:
      - select:
          kind: AuthorizationPolicy
        fieldPaths:
          - metadata.namespace  # Replace the namespace field
          - spec.rules[0].from[0].source.namespaces[0]  # Replace the rule's namespace
  - source:
      kind: ConfigMap
      name: app-config
      fieldPath: data.AUTH_POLICY_NAME
    targets:
      - select:
          kind: AuthorizationPolicy
        fieldPaths:
          - metadata.name  # Replace the name field
