# ./apps/app1/kustomization.yaml
resources:
  - allow-intra-namespace.yaml

# Define custom configuration for the app (host and exact URL)
configMapGenerator:
  - name: app2-config
    literals:
      - host=app1-example.com
      - exact_url=/app1-service