name: virtualservice-helmchart
namespace: ind-ns2
hosts:
  - "*"
gateway: virtualservice-helmchart
uri: /virtualservice-helmchart
destination:
  host: virtualservice-helmchart
  port: 80
serviceaccount:
  create: true
  name: serviceaccount-argocd-app
  namespace: ind-ns1