apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
{{ toYaml .Values.namespace.labels | indent 4 }}
  annotations:
{{ toYaml .Values.namespace.annotations | indent 4 }}
