apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.service.namespace }}
  labels:
{{ toYaml .Values.service.labels | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
{{ toYaml .Values.service.selector | indent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
