apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.virtualservice.name }}
spec:
  hosts:
  {{- range .Values.virtualservice.hosts }}
  - {{ . | quote }}
  {{- end }}
  gateways:
  - {{ .Values.virtualservice.gateway }}
  http:
  - match:
    - uri:
        exact: {{ .Values.virtualservice.uri }}
    route:
    - destination:
        host: {{ .Values.virtualservice.destination.host }}
        port:
          number: {{ .Values.virtualservice.destination.port }}