name: Package and Publish Helm Charts - Manual Trigger

on:
  workflow_dispatch:
    inputs:
      deployment_branch:
        description: 'Branch to deploy charts from'
        required: true
        type: choice
        options:
          - main
          - rel/release1.0
        default: main

      environment:
        description: 'Target deployment environment'
        required: true
        type: choice
        options:
          - development
          - innovation
        default: innovation

jobs:
  publish-charts:
    runs-on: ubuntu-latest
    outputs:
      folders: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.deployment_branch }}

      - name: Set matrix for basecharts
        id: set-matrix
        run: |
          folders=$(find basecharts -mindepth 1 -maxdepth 1 -type d | jq -R -s -c 'split("\n") | map(select(length > 0))')
          echo "matrix=$folders"
          echo "matrix=$folders" >> $GITHUB_OUTPUT

