name: Track Folder Changes

on:
  push:
    paths:
      - 'workloads/**'

jobs:
  track-changes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Track changes in src folder
      run: |
        echo "Changes detected in the src folder"
        # Add your custom logic here, such as running tests or building the project